name: financial_companion
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  google_generative_ai: ^0.4.7
  intl: ^0.19.0
  http: ^1.1.0
  notifications: ^3.1.0

  # UI + utils
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  table_calendar: ^3.0.9
  fl_chart: ^0.68.0
  flutter_colorpicker: ^1.0.3
  image_picker: ^1.0.7

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  cloud_functions: ^6.0.1
  firebase_storage: ^13.0.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/pets/
    - assets/avatars/

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/fonts/Poppins-Regular.ttf
        - asset: lib/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: lib/fonts/Poppins-Italic.ttf
          style: italic
